name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
  test:
    name: Test app
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Docker login
        run: echo "${{ secrets.GITLAB_PASS }}" | docker login registry.gitlab.com -u "${{ secrets.GITLAB_USER }}" --password-stdin
      - name: Pull example image
        run: docker pull alpine:latest
      - name: Tag example image
        run: docker tag alpine:latest registry.gitlab.com/vleedev/gitlab-registry-controller:alpine-latest
      - name: Push example image
        run: docker push registry.gitlab.com/vleedev/gitlab-registry-controller:alpine-latest
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Delete specific image
        run: go run main.go -domain https://gitlab.example.com/api/v4 -authToken "${{ secrets.GITLAB_PASS }}" -nameSpace vleedev -projectName gitlab-registry-controller -specificTag alpine-latest
